### PR TITLE
chore: bump ansys-sphinx-theme versions

### PR DESCRIPTION
**Pull request by tmpbeing**
Also removed the poetry.lock associated to the updated pyproject.toml as I can't properly update them and I'd argue they don't need to be in the templates.

### CODE REVIEW

**Comment by germa89** [comment]
I'm not sure about the `lock` file.. pinging @jorgepiloto

**Comment by tmpbeing** [comment]
Seems the CI fails. I never used cookiecutter. I wonder if we could get the lock built when the template is activated ?

My main issue with having poetry.lock in the template is I can't run `poetry lock` in the template folder since the `pyproject.toml` isn't valid because of the templating parts.

**Comment by germa89** [comment]
The CI fail because it seems the tests check for the lock file:

https://github.com/ansys/ansys-templates/actions/runs/7275956493/job/19824766455?pr=418#step:5:315

Again, i'm not skilful enough on this. I will leave it up to @jorgepiloto to give more feedback on why the lock file is needed.

**Review by iazehaf — CHANGES_REQUESTED** [review]
@tmpbeing the poetry.lock files are important, especially for the `solution `and `osl_solution `templates:

1. The installation  is quicker as the dependency resolution is done. 
2. They avoid installation errors by pining the packages.

**Comment by tmpbeing** [comment]
Alright, thanks. I've no idea how to update them so feel free to either take it over or close the PR.

**Comment by tmpbeing** [comment]
Closing in favour of https://github.com/ansys/ansys-templates/pull/422

**Pull request closed without merging**
