### PR TITLE
tweak: use open instead of your_browser_name

### PR DESCRIPTION
**Pull request by tmpbeing**
The open command will use the default system browser to open the file https://linux.die.net/man/1/open

### CODE REVIEW

**Review by germa89 — APPROVED** [review]
LGTM.

**Review by AlejandroFernandezLuces — COMMENTED** [review]
I think this change makes the command not being SO agnostic right? I don't think windows has the open command

**Comment by germa89** [comment]
> I think this change makes the command not being SO agnostic right? I don't think windows has the open command

I think it doesnt, anyways, the changes proposed here only affect the linux parts.

**Comment by germa89** [comment]
Code-cov is failing... Fixing this in https://github.com/ansys/ansys-templates/pull/419

**Comment by tmpbeing** [comment]
> I think this change makes the command not being SO agnostic right? I don't think windows has the open command

You're right, unfortunate. It's not clear to me whether I should close the PR or not so I'll leave it in your hands.

**Comment by germa89** [comment]
> > I think this change makes the command not being SO agnostic right? I don't think windows has the open command
> 
> You're right, unfortunate. It's not clear to me whether I should close the PR or not so I'll leave it in your hands.

I think it is fine.

**Comment by AlejandroFernandezLuces** [comment]
> > I think this change makes the command not being SO agnostic right? I don't think windows has the open command
> 
> You're right, unfortunate. It's not clear to me whether I should close the PR or not so I'll leave it in your hands.

It should be good to go since it only affects Linux parts as @germa89 said. Let's go ahead with this 🙂

**Review by AlejandroFernandezLuces — APPROVED** [review]

**Review by MaxJPRey — APPROVED** [review]
Thanks @tmpbeing for the suggestion.

**Comment by jorgepiloto** [comment]
Thank you all your contributions to the project 🚀

**Pull request merged**
