### PR TITLE
Fix uvicorn location in optislang template

### PR DESCRIPTION
**Pull request by pierreansys**
uvicorn.exe is not available in the optislang environment, so let's use python to start uvicorn  via python -m uvicorn

### CODE REVIEW

**Review by iazehaf — CHANGES_REQUESTED** [review]
Tested. Not working.

**Comment by JoseRamonRodriguez** [comment]
> Tested. Not working.

@iazehaf Pierre and I tested it individually and it worked. Should we have a call?

**Comment by pierreansys** [comment]
> Tested. Not working.

Yes sorry, I've made a stupid mistake in the PR. This should be fixed now

**Review by asbfall — APPROVED** [review]

**Comment by iazehaf** [comment]
> > Tested. Not working.
> 
> @iazehaf Pierre and I tested it individually and it worked. Should we have a call?

@JoseRamonRodriguez @pierreansys let me test with the latest changes.

**Review by iazehaf — APPROVED** [review]
Tested. Working.

**Pull request merged**
