### PR TITLE
fix: update CODEOWNERS

### PR DESCRIPTION
**Pull request by nick-marnik**
I created a [new team](https://github.com/orgs/ansys/teams/optislang-development-team/members) based on the contents of the [internal team](https://github.com/orgs/Solution-Applications/teams/optislang-development-team)

My understanding is that this new team will be owned by... @dazwhite ? There are a few people I couldn't add to the new ansys group because they aren't yet a member of the Ansys organization. I'll defer to someone else to take ownership of the team and manage it moving forward.

This PR cannot be merged until @ansys/optislang-development-team is given write access to this repository - @asbfall is that something you have access to change?

### CODE REVIEW

**Comment by JoseRamonRodriguez** [comment]
@nick-marnik I don't think this is needed as the oSL template is going to be moved to a private repository very soon

**Comment by nick-marnik** [comment]
@JoseRamonRodriguez Do you have a timeline of when this change will happen? If it's easier, we can simply remove the osl_solution template from the CODEOWNERS file entirely. The maintainers group isn't the right audience and everyone gets email notifications for all PRs/comments/etc. that aren't relevant to us.

**Comment by JoseRamonRodriguez** [comment]
> @JoseRamonRodriguez Do you have a timeline of when this change will happen? If it's easier, we can simply remove the osl_solution template from the CODEOWNERS file entirely. The maintainers group isn't the right audience and everyone gets email notifications for all PRs/comments/etc. that aren't relevant to us.

@nick-marnik the code has been migrated to ansys internal. The only remaining thing is to remove it from here ([this ticket](https://github.com/ansys-internal/saf-osl-app-builder/issues/167) will take care of it)

**Comment by nick-marnik** [comment]
Replaced by https://github.com/ansys/ansys-templates/pull/425

**Pull request closed without merging**
