### PR TITLE
fix: update pydocstyle in ``pyproject.toml`` file

### LINKED ISSUE #476: `pydocstyle` missing configuration for numpydoc convention
Currently in repos based on `ansys-templates`, the numpydoc docstring checks take place only when building the docs. I believe `pydocstyle` should be configured out of the box for the numpydoc convention as well, otherwise it is unable to identify when docstrings don't follow the PyAnsys enforced style. This renders `pydocstyle` mostly useless in my understanding.

I am aware of two ways to do that, following [PyAnsys doc style guide](https://dev.docs.pyansys.com/doc-style/formatting-tools.html#the-pydocstyle-tool), can add this to `pyproject.toml`:
```
[tool.pydocstyle]
convention = "numpy"
```

or add this to `.pre-commit-config.yaml` in the last lines of the `pydocstyle` block:
```
args:
  - --convention=numpy
```

As discussed @RobPasMue

### PR DESCRIPTION
**Pull request by Revathyvenugopal162**
fix #476

### CODE REVIEW

**Review by MaxJPRey — APPROVED** [review]
LGTM.

**Review by SMoraisAnsys — APPROVED** [review]
LGTM

**Comment by MaxJPRey** [comment]
@Revathyvenugopal162 , @jorgepiloto, @SMoraisAnsys , @RobPasMue .
This is kind of best practices. I think we should remind it to our colleagues in the weekly meeting, because it would help us to improve the quality of the docstrings in the entire ecosystem.

**Comment by RobPasMue** [comment]
Sure sounds good!

**Pull request merged**
